class AppStrings {
  static const Map WEEK_DAYS = {
    1: 'poniedziałek',
    2: 'wtorek',
    3: 'środa',
    4: 'czwartek',
    5: 'piątek',
    6: 'sobota',
    7: 'niedziela',
  };
  static const String NAME = 'Imię',
      APP_TITLE = 'Pomocnik',
      SURNAME = 'Nazwisko',
      ALPHABETIC_ASCENDING = 'Alfabetycznie rosnąco',
      ALPHABETIC_DESCENDING = 'Alfabetycznie malejąco',
      ABOUT = 'O programie',
      ABSENT = 'Nieobecny',
      AGE = 'Wiek',
      ADD = 'Dodaj',
      AMOUNT = 'sumą',
      BILLS = 'Rachunki',
      ADD_PARENT = 'Dodaj rodzica',
      ADD_CONTACT = 'Dodaj kontakt',
      ADD_CLASSES_TYPE = 'Dodaj typ zajęć',
      ADD_CLASSES = 'Dodaj zajęcia',
      ADD_SIBLING = 'Dodaj rodzeństwo',
      ADD_GROUP = 'Dodaj grupę',
      ADD_PARTICIPANTS = 'Dodaj uczestników',
      ADD_STUDENT = 'Dodaj ucznia',
      ADDED_NEW_CONTACT = 'Dodano nowy kontakt',
      ATTENDANCE_LIST = 'Lista obecności',
      ATTENDANCES = 'Obecności',
      AT_TIME = 'o godzinie',
      ARE_YOU_SURE_TO_REMOVE = 'Czy na pewno usunąć',
      BILANCE = 'Saldo',
      CLASSES_ADDRESS = 'Adres zajęć',
      CLASSES_TYPE = 'Typ zajęć',
      CALL = 'Zadzwoń',
      ARE_YOU_SURE_YOU_WANT_REMOVE_A_CONTACT =
          'Czy na pewno chcesz usunąć kontakt',
      SEND_MESSAGE = 'SMS',
      AND = 'i',
      TO = 'do',
      CANCEL = 'Anuluj',
      CANCEL_ADDING_CONTACTS = 'Anuluj dodawanie kontaktów',
      CITY = 'Miasto',
      CLASSES = 'Zajęcia',
      CLASSES_CONDUCTED = 'Przeprowadzone zajęcia',
      CURRENT_STATE_OF_BALANCE = 'Aktualny stan konta',
      MANAGE_CLASS_TYPES = 'Zarządzanie typami zajęć',
      MANAGEMENT = 'Zarządzanie',
      MANAGE_GROUPS = 'Zarządzanie grupami',
      MANAGE_CLASSES = 'Zarządzanie przeprowadzonymi zajęciami',
      MANAGE_FINANCES = 'Zarządzanie finansami',
      NUMBER_OF_STUDENTS_CONTACTS = 'Ilość numerów uczniów',
      NUMBER_OF_PARENTS_CONTACTS = 'Ilość numerów rodziców',
      CONTACTS = 'Kontakty',
      CONTACT = 'Kontakt',
      CONFIRM_REMOVING = 'Potwierdź usunięcie',
      CREATE_STUDENT = 'Utwórz ucznia',
      CREATE_PARENT = 'Utwórz rodzica',
      CREATE_CONTACT = 'Utwórz kontakt',
      CREATED_NEW_CLASS_TYPE = 'Utworzono nowy typ',
      CREATED_NEW_CLASSES = 'Utworzono nowe',
      CHILDREN = 'Dzieci',
      CHOSE_DATE = 'Wybierz datę',
      CHOSE_TIME = 'Wybierz godzinę',
      CHOSE_DATE_OF_CLASSES = 'Wybierz termin zajęć',
      CHANGE_SROTING = 'Zmień sortowanie',
      CURRENCY = 'zł',
      DATABASE_DIRECTORY = 'objectbox',
      DATE_OF_CLASSES = 'Data zajęć',
      DELETE = 'Usuń',
      DELETED_STUDENT = 'Usunięto studenta',
      DETAILS = 'Szczegóły',
      DISCONNECT = 'Rozłącz',
      DATABASE_FILE_NAME = 'data',
      DATABASE_EXTENSION = 'mdb',
      DATABASE_FULL_FILE_NAME = '$DATABASE_FILE_NAME.$DATABASE_EXTENSION',
      DATE = 'Data',
      TIME = 'Czas',
      EDIT = 'Edytuj',
      EDITED = 'Edytowano',
      ENTER_AMOUNT = 'Podaj kwotę',
      EXPORT_DATABASE = 'Eksportuj bazę danych',
      EXPORTING_DATABASE_TITLE = 'Eksport bazy danych',
      EXPORTING_DATABASE_TEXT = 'Wybierz lokalizację dla bazy danych',
      UPDATED = 'Zaktualizowano',
      FAIL_TO_ADD_NEW_PARENT_TO_DATABASE =
          'Nie udało się dodać nowego rodzica do bazy danych.',
      FLAT_NUMBER = 'Numer mieszkania',
      FINANCE = 'Finanse',
      FUND_ACCOUNT = 'Zasil konto',
      FUND = 'Zasil',
      FUNCTION = 'funkcja',
      FONT_ARCHITECTS_DAUGHTER = 'ArchitectsDaughter',
      FONT_CROISSANT_ONE = 'CroissantOne',
      FONT_LIBERATION_SERIF = 'LiberationSerif',
      FONT_LUCIAN_SCHOENSHRIFT = 'LucianSchoenschriftCAT',
      FONT_NEW_ATHENA_UNICODE = 'NewNthenaUnicode',
      ADD_FUNCTION = 'add function',
      REMOVE_FUNCTION = 'remove function',
      FIND_CONTACT = 'Szukaj kontaktu',
      FIND_STUDENT = 'Szukaj ucznia',
      GROUP_NAME = 'Nazwa grupy',
      GROUP = 'Grupa',
      GROUPS = 'Grupy',
      GROUP_OF_CLASSES = 'Grupa zajęć',
      HOUSE_NUMBER = 'Numer domu',
      ID = 'ID',
      IN_DAY = 'w dniu',
      IMPORT_DATABASE = 'Importuj bazę danych',
      LIST = 'Lista',
      LIST_OF_TYPES = 'Lista typów',
      LIST_OF_CLASSES_CONDUCTED = 'Lista przeprowadzonych zajęć',
      NAME_OF_CLASSES_TYPE = 'Nazwa typu zajęć',
      NEW_TYPE = 'Nowy typ',
      NEW_GROUP = 'nową grupę',
      NUMBER_OF_CHILDREN = 'Ilość dzieci',
      NUMBER_OF_GROUPS = 'Ilość grup',
      NUMBER_OF_CLASSES = 'Ilość zajęć',
      NUMBER_OF_SIGNED_UP = 'Ilość zapisanych uczniów',
      NUMBER_OF_STUDENTS = 'Ilość uczniów',
      NUMBER_OF_SIBLINGS = 'Ilość rodzeństwa',
      NUMBER_OF_ATTENDANCES = 'Ilość obecności',
      NUMBER_OF_CLASS_TYPES = 'Ilość typów zajęć',
      NUMBER_OF_PHONES = 'Ilość numerów telefonów',
      NONE_TYPE = 'Brak typu',
      MANAGE_DATABASE = 'Zarządzaj bazą danych',
      TEACHER = 'Nauczyciel',
      PARENT = 'Rodzic',
      STUDENT = 'Uczeń',
      OK = 'OK',
      ON_DATE = 'w dniu',
      PARENTS = 'Rodzice',
      PARTICIPANTS = 'Uczestnicy',
      PAID = 'Zapłacono',
      PAID_CLASSES = 'Zapłaconych zajęć',
      UNPAID_CLASSES = 'Niezapłaconych zajęć',
      PRESENT = 'Obecny',
      PRESENTS_AT_THE_CLASSSES = 'Obecni na zajęciach',
      UNPAID = 'Nie zapłacono',
      PERSONS_IN_GROUP = 'Osoby w grupie',
      PHONES = 'Telefony',
      PHONE_NUMBER = 'Numer telefonu',
      PHONE_NAME = 'Nazwa kontaktu',
      PHONE_BOOK = 'Książka telefoniczna',
      PRICE_FOR_EACH = 'Cena za jedne zajęcia',
      PRICE_FOR_MONTH = 'Cena za miesiąc',
      REMOVED_FROM_DATABASE = 'usnięto z bazy danych',
      REMOVED = 'usunięta',
      STUDENT_AGE = 'Wiek ucznia',
      SIBLINGS = 'Rodzeństwo',
      SUCCESFULLY_ADDED = 'Pomyślnie dodano',
      SUCCESFULLY = 'pomyślnie',
      SUCCESFULLY_UPDATED_STUDENT = 'Pomyślnie edyowano ucznia',
      STREET = 'Ulica',
      SIGNED_UP_FOR_CLASSES = 'Zapisani na zajęcia',
      TO_DATABASE = 'do bazy danych',
      TO_PAY = 'Do zapłaty',
      TOTAL_PAID = 'Łącznie zapłacono',
      TOTAL_UNPAID = 'Łącznie niezapłacono',
      THEY_ARENT_SIBLINGS = 'nie są już rodzeństwem!',
      THEY_ARE_SIBLINGS = 'są teraz rodzeństwem',
      THEY_ARE_FAMILY_NOW = 'są teraz rodziną',
      THEY_ARENT_FAMILY = 'nie są już rodziną',
      YEARS = 'lat',
      CLASSES_TYPE_KEY = 'classes_type',
      STUDENT_KEY = 'student',
      STUDENT_MANAGEMENT = 'Zarządzanie uczniami',
      WRITTEN = 'Zapisani',
      STUDENTS_LIST = 'Lista uczniów',
      STUDENT_ACCOUNT = 'Konto ucznia',
      STATISTICS = 'Statystyki',
      SHARE_DATABASE = 'Udostępnij bazę danych',
      BILLS_LIST = 'Lista rachunków',
      DATA_HAS_BEEN_UPDATED = 'Zakutalizowano dane',
      FUNDED_ACCOUNT = 'Zasiono konto',
      ERROR_MESSAGE_CHECK_FIELDS_FILL =
          'Wystąpił błąd, spradź poprawność wypełnienia pól!',
      YES = 'Tak',
      NO = 'Nie',
      SELECT_THE_FILE_TO_BE_IMPORTED =
          "Wybierz plik który ma zostać zaimportowany",
      AFTER_IMPORTING_CORRECTLY_RESTAT_THE_APP =
          'Po prawidłowej zaimportowaniu, należy uruchomić aplikację ponownie.',
      OTHERWISE_THE_DB_WILL_NOT_BE_IMPORTED_CORRECTLY =
          'W przeciwnym wypadku nie zostanie poprawnie zaimportowana baza.',
      CHOSEN_FILE_NEED_TO_HAVE_SPECIFIC_EXTENSIONS =
          'Wybierany plik musi posiadać rozszerzenie:',
      DATABASE_WAS_SUCCESSFULLY_IMPORTED =
          'Poprawnie zaimportowano bazę danych.',
      REMOVE_CLASSES_WARNING_MESSAGE =
          'Potwierdzenie usunięcia sprawi że wszystkie rachunki i obecności z tych zajęć zostaną usunięte bezpowrotnie. Opłacone zajęcia nie zwrócą środków na saldo uczestników za zajęcia w których są potwierdzone obecności.';
}
