class Strings{
  static const String NAME = 'Imię',
  SURNAME = 'Nazwisko',
  AGE = 'Wiek',
  ADD = 'Dodaj',
  ADD_PARENT = 'Dodaj rodzica',
  ADD_CONTACT = 'Dodaj kontakt',
  ADD_SIBLING = 'Dodaj rodzeństwo',
  CANCEL = 'Anuluj',
  CANCEL_ADDING_CONTACTS = 'Anuluj dodawanie kontaktów',
  CONTACTS = 'Kontakty',
  CREATE_STUDENT = 'Utwórz ucznia',
  CREATE_PARENT = 'Utwórz rodzica',
  CHILDREN = 'Dzieci',
  DELETE = 'Usuń',
  DATABASE_NAME = 'objectbox',
  EDIT = 'Edytuj',
  ID = 'ID',
  OK = 'OK',
  PARENTS = 'Rodzice',
  PHONE_NUMBER = 'Numer telefonu',
  PHONE_NAME = 'Nazwa kontaktu',
  SIBLINGS = 'Rodzeństwo';
}