class Strings {
  static const String NAME = 'Imię',
      SURNAME = 'Nazwisko',
      AGE = 'Wiek',
      ADD = 'Dodaj',
      ADD_PARENT = 'Dodaj rodzica',
      ADD_CONTACT = 'Dodaj kontakt',
      ADD_SIBLING = 'Dodaj rodzeństwo',
      AND = 'i',
      CANCEL = 'Anuluj',
      CANCEL_ADDING_CONTACTS = 'Anuluj dodawanie kontaktów',
      CONTACTS = 'Kontakty',
      CREATE_STUDENT = 'Utwórz ucznia',
      CREATE_PARENT = 'Utwórz rodzica',
      CHILDREN = 'Dzieci',
      DATABASE_NAME = 'objectbox',
      DELETE = 'Usuń',
      DISCONNECT = 'Rozłącz',
      EDIT = 'Edytuj',
      ID = 'ID',
      OK = 'OK',
      PARENTS = 'Rodzice',
      PHONE_NUMBER = 'Numer telefonu',
      PHONE_NAME = 'Nazwa kontaktu',
      SIBLINGS = 'Rodzeństwo',
      THEY_ARENT_SIBLINGS = 'nie są już rodzeństwem!';
}
